name: Run multiple jobs

on: push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
        - name: Install cosway program
          run: sudo apt-get install cowsay -y

        - name: Execute cosway cwd
          run: cowsay -f cow "The cow jumped over the moon! Mooo ... " >> cow.txt

        - name: Sleep for 30 seconds
          run: sleep 30

    test_job_2:
        runs-on: ubuntu-latest
        steps:
            - name: Sleep 10 seconds
              run: sleep 10

            - name: Test file exists
              run: grep -i "cow" cow.txt

    deploy_job_3:
        runs-on: ubuntu-latest
        steps:
            - name: Read file
              run: cat cow.txt

            - name: Deploy
              run: echo Deploying ...