name: Run multiple jobs

on: push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
        - name: Install cowsay program
          run: sudo apt-get install cowsay -y

        - name: Execute cowsay cwd
          run: cowsay -f sheep "Baa baa black sheep! Baaa ... " >> sheep.txt

        - name: Sleep for 30 seconds
          run: sleep 30

    test_job_2:
        needs: build_job_1
        runs-on: ubuntu-latest
        steps:
            - name: Sleep 10 seconds
              run: sleep 10

            - name: Test file exists
              run: grep -i "sheep" sheep.txt

    deploy_job_3:
        needs: test_job_2
        runs-on: ubuntu-latest
        steps:
            - name: Read file
              run: cat sheep.txt

            - name: Deploy
              run: echo Deploying ...