name: My first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v6

        - name: Welcome message
          run: echo "My first actions job"

        - name: List files
          run: ls

        - name: Show contents
          run: cat README.md